volumes:
  foobar_composer:
    external: true
  foobar_npm:
    external: true
  mariadb_data:

services:
  php:
    volumes:
      - ./:/var/www/
      - foobar_composer:/home/code/.composer
      - foobar_npm:/home/code/.npm

  worker:
    volumes:
      - ./:/var/www/
      - foobar_composer:/home/code/.composer
      - foobar_npm:/home/code/.npm

  nginx:
    volumes:
      - ./public:/var/www/public

  mariadb:
    volumes:
      - mariadb_data:/var/lib/mysql:Z
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
