# Config options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - dependencies
  - package-ecosystem: "docker"
    directory: "/php"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
