name: Setup PHP
description: Compose action that sets up PHP and Composer

inputs:
  php-version:
    description: The PHP version
    default: "{{ if eq PhpVersion "8.3"}}8.3{{ else if eq PhpVersion "8.2"}}8.2{{ else }}8.4{{ end }}"
  coverage:
    description: Set PHP coverage driver
    default: none
  extensions:
    description: Set PHP extensions
  github-token:
    description: Add a Github Token which will be used for Composer auth

runs:
  using: composite
  steps:
    - name: Get composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Restore Composer cache
      id: composer-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          {{`${{ steps.composer-cache-dir.outputs.dir }}`}}
          vendor
        key: {{`${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}`}}
        restore-keys: {{`${{ runner.os }}-composer-`}}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: {{`${{ inputs.php-version }}`}}
        coverage: {{`${{ inputs.coverage }}`}}
        extensions: {{`${{ inputs.extensions }}`}}
        github-token: {{`${{ inputs.github-token }}`}}

    - name: Install dependencies
      shell: bash
      run: composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

    - name: Copy .env.example to .env
      shell: bash
      run: cp .env.example .env

    - name: Copy .env.testing.example to .env.testing
      shell: bash
      run: cp .env.testing.example .env.testing

    - name: Update .env.testing DB_HOST
      shell: bash
      run: sed -i 's#^\(DB_HOST=\).*#\1127.0.0.1#' .env.testing

    - name: Save Composer cache
      if: {{`${{ steps.composer-cache.outputs.cache-hit != 'true' }}`}}
      uses: actions/cache/save@v4
      with:
        path: |
          {{`${{ steps.composer-cache-dir.outputs.dir }}`}}
          vendor
        key: {{`${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}`}}
